PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX cc:      <https://cargo-cicd.rs/ontology/>

SELECT ?noun ?verb ?cli_command ?description ?feature_required
WHERE {
    ?cap a cc:Capability ;
         cc:noun           ?noun ;
         cc:verb           ?verb ;
         cc:cliCommand     ?cli_command ;
         dcterms:description ?description .
    OPTIONAL { ?cap cc:requiresFeature ?feature_required }
}
ORDER BY ?noun ?verb
