[profile.default]
retries = 0
slow-timeout = { period = "60s", terminate-after = 3 }
fail-fast = false

[profile.ci]
retries = 1
slow-timeout = { period = "60s", terminate-after = 3, grace-period = "5s" }
fail-fast = false
status-level = "all"
final-status-level = "flaky"

[profile.ci.junit]
path = "target/nextest/ci/junit.xml"
