coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 50%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "**/main.rs"
  - "**/*.snap"
  - "fuzz/**/*"
